services:
  app:
    build: .
    container_name: python-server
    volumes:
      - .:/workspace
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: postgres:16
    container_name: postgres-server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres_data: